from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

# adding additional default values built on top of the default values in detectron2

_CC = _C

# FREEZE Parameters
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.PROPOSAL_GENERATOR.FREEZE = False
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False

# choose from "FastRCNNOutputLayers" and "CosineSimOutputLayers"
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
# scale of cosine similarity (set to -1 for learnable scale)
_CC.MODEL.ROI_HEADS.COSINE_SCALE = 20.0
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8

# Backward Compatible options.
_CC.MUTE_HEADER = True

_CC.MODEL.ROI_BOX_HEAD.BOX_REG_WEIGHT = 1.0
_CC.MODEL.ROI_BOX_HEAD.BOX_CLS_WEIGHT = 1.0

_CC.MODEL.ROI_BOX_HEAD.SUB_FC_DIM = 1024

# perform Supervised Contrastive Loss within batch
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH = CN({'ENABLED': False})  # to be used to enable contrastive loss for double head
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.MLP_FEATURE_DIM = 128
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.TEMPERATURE = 0.1
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.LOSS_WEIGHT = 1.0
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.DECAY = CN({'ENABLED': False})
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.DECAY.STEPS = [8000, 16000]
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.DECAY.RATE = 0.2
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.IOU_THRESHOLD = 0.5
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.LOSS_VERSION = 'V1'
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.REWEIGHT_FUNC = 'none'

_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.STORAGE = CN({'ENABLED': False})
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.STORAGE.START = 3000
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.STORAGE.IOU_THRESHOLD = 0.8

# use classes prototypes obtained from base training.
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE = CN()  # use with ContrastiveROIHeadsWithPrototype
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.DATASET = 'PASCAL VOC'
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.PATH = ''
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.DISABLE_PROTOTYPE_GRAD = True
# train the contrastive head only
_CC.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.HEAD_ONLY = False

