_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "/home/ashutosh_a/FSCE/VOCMODELS/model_second_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputAttentionLayers"
    FREEZE_FEAT: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  TRAIN: ('voc_2007_trainval_all2_1shot_seed13',)
  TEST: ('voc_2007_test_all2',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (2000,)
  MAX_ITER: 3500
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 20

TEST:
  EVAL_PERIOD: 700

OUTPUT_DIR: "checkpoints/voc/ablation/split2/1shot_baseline_seed13_fsar"
