_BASE_: "../../Base-RCNN-FPN.yaml"
SEED: 59443813

MODEL:
  WEIGHTS: "checkpoints/idd/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NUM_CLASSES: 14
    OUTPUT_LAYER: "APFCosineMarginOutputLayer" #"CosineSimOutputAttentionLayers"
    FREEZE_FEAT: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

INPUT:
  CROP:
    ENABLED: TRUE
  MIN_SIZE_TRAIN: (736, 768, 800, 1080)
  MIN_SIZE_TEST: 1080

DATASETS:
  TRAIN: ('idd_2019_trainval_all1_10shot',)
  TEST: ('idd_2019_val_all1',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (3500,)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 20

TEST:
  EVAL_PERIOD: 700

OUTPUT_DIR: "checkpoints/idd/10shot_AGCM_IoU_0.4"
