_BASE_: "faster_rcnn_R_101_FPN_ETF_pre1_10shot.yaml"
MODEL:
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NAME: "ContrastiveDistillROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "FastRCNNContrastiveDistillOutputs" 
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_VERSION: "FL+FLVMI"
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [10000, 16000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
LOSS:
  ADJUST_STAGE: 'distill'
SOLVER:
  BASE_LR: 0.04
OUTPUT_DIR: "checkpoints/voc/distill/t1"