_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
SEED: 37756442

INPUT:
  MIN_SIZE_TRAIN: (736, 768, 800, 1080)
  MIN_SIZE_TEST: 1080

DATASETS:
  TRAIN: ('idd_2019_train',)
  TEST: ('idd_2019_val',)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (8000,13000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 700

OUTPUT_DIR: "checkpoints/idd/faster_rcnn/all_frcnn_ce"