_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 10
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_VERSION: "GC"
      TEMPERATURE: 0.7
      LOSS_WEIGHT: 0.01
      DECAY:
        ENABLED: True
        STEPS: [8000, 12000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
SEED: 37756442

INPUT:
  MIN_SIZE_TRAIN: (736, 768, 800, 1080)
  MIN_SIZE_TEST: 1080

DATASETS:
  TRAIN: ('idd_2019_train',)
  TEST: ('idd_2019_val',)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  #GAMMA: 0.5
  STEPS: (12000,17000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 2000

OUTPUT_DIR: "checkpoints/idd/faster_rcnn/all_GC_0.7_IoU_0.7"