_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
INPUT:
  MIN_SIZE_TRAIN: (736, 768, 800, 1080)
  MIN_SIZE_TEST: 1080
DATASETS:
  TRAIN: ('idd_2019_trainval_base1',)
  TEST: ('idd_2019_val_base1',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
OUTPUT_DIR: "checkpoints/idd/faster_rcnn/faster_rcnn_R_101_FPN_base1"
