_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "APFCosineMarginOutputLayer"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 0.0

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: True

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_10shot',)
  TEST: ('voc_2007_test_all1',)
SEED: 28655059

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (8000,13000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 6000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 700

OUTPUT_DIR: "checkpoints/voc/10shot_CL_IoU_attn"